[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_flags = -Wl,-Teagle.flash.4m2m.ld
lib_deps =
  siruli/MAX6675@^2.1.0
  br3ttb/PID@^1.2.1
  adafruit/Adafruit RGB LCD Shield Library@^1.2.2
