[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_flags = -Wl,-Teagle.flash.4m2m.ld
lib_deps = 
  adafruit/Adafruit MAX6675 Library@^1.1.0
  br3ttb/PID@^1.2.1
  robotdyn/LCD_RGB_Keypad@^1.0.0
  ESP8266HTTPClient
  ESP8266WebServer
  EEPROM